In [74]:
import numpy as np
from scipy.special import spence
import matplotlib.pyplot as plt

In [63]:
mp = .938272081
me = 0.5109989461 * 0.001
alpha = 1/137.036

## Reproducing Virtuals (Marc's elastic paper)

In [226]:
Ee, thetae, Q2, delta_vertex, delta_vac, delta_R, delta_1, delta_2, delta_tot, delta_EXP =  np.loadtxt("marc_table.csv").T

In [227]:
delta_vertex_reproduced = alpha/np.pi * (1.5 * np.log(Q2/me**2) -2 - 0.5*np.log(Q2/me**2)**2 + np.pi**2/6)
delta_vac_reproduced    = alpha/np.pi * (2./3.) * (-5./3. + np.log(Q2/me**2))

In [228]:
Eetilde      = Ee
Eeprime_el   = E_e / ( 1 + E_e/ (mp * (1-np.cos(theta_e) ) ) )
Eeprime      = Eeprime_el# + 0.01*Ee
Eeprimetilde = Eeprime
deltaEs      = 0.01*Ee
delta_r1 = alpha/np.pi * np.log(deltaEs**2 /Eetilde/Eeprimetilde) * (np.log(Q2/me**2)-1)

sinsquared_thetatetilde_half = np.sin(np.radians(thetae)/2)**2
cossquared_thetatetilde_half = 1 - sinsquared_thetatetilde_half

delta_r2 = alpha/np.pi* (-0.5* (np.log(Eetilde/Eeprimetilde)**2) + 0.5 * np.log(Q2/me**2)**2 - np.pi**2/3 + spence(1 - cossquared_thetatetilde_half))

In [219]:
rho = np.sqrt(Q2 + 4*mp**2)
aks = (np.sqrt(Q2) + rho)**2/4/mp**2
eta = 0.01
delta_1_reproduced   = 2*alpha/np.pi * (np.log(4*(deltaEs)**2/Q2/aks) * np.log(eta) + spence(1-(1-eta/aks)) - spence(1-(1-1/eta/aks)) ) 

delta_2_reproduced   = alpha/np.pi * ( np.log(4*(deltaEs)**2/mp**2)*(Eprime_p/pprime_p*np.log(aks)-1) + 1 
                        + Eprime_p/pprime_p * (-0.5*np.log(aks)**2 - np.log(aks)*np.log(rho**2/M**2) + np.log(aks)
                        - spence( 1 - (1-1/aks/aks)) +2*spence( 1 - (-1/aks)) + np.pi**2/6 ) ) #A76

NameError: name 'Eprime_p' is not defined

In [222]:
cossquared_thetatetilde_half

array([0.8792947 , 0.80659142, 0.98197811, 0.95740937, 0.92193   ,
       0.86621204, 0.98312066, 0.97161133, 0.9569146 , 0.93752123,
       0.91077372])

In [230]:
delta_r2 + delta_r1, delta_R

(array([-0.0174266 , -0.00207379,  0.05543917,  0.07065605,  0.07994859,
         0.0866225 ,  0.08157654,  0.09139447,  0.09854753,  0.1041798 ,
         0.10880836]),
 array([-0.0453, -0.0245, -0.026 ,  0.0018,  0.03  ,  0.0623, -0.0097,
         0.0092,  0.0284,  0.049 ,  0.0718]))

In [234]:
spence(1-(1-eta/aks))

array([1.60703627, 1.61291304, 1.62102196, 1.62752193, 1.63100886,
       1.63324653, 1.62752193, 1.63100886, 1.63324653, 1.63482274,
       1.63600041])

## Case 1) Ruonan's thesis

In [58]:
E_beam = 4.55974
Q2     = 0.332
# s      = 2 * mp * E_beam
W      = 1.232
s      = W**2

In [59]:
nu = (s - mp**2 +Q2)/2/mp

In [60]:
q_cm = Q2 + (s-Q2 -mp**2)**2/4/s

In [61]:
qprime_cm = (s-mp**2)/2/W

In [62]:
q_cm, qprime_cm

(0.34736930774942615, 0.2587132719220493)

In [63]:
E_e = E_beam - nu

In [64]:
E_beamx  = 0
E_beamy  = 0
E_beamz  = np.sqrt(E_beam **2 - me**2)

In [65]:
E_py = 0
E_pz = E_e * (1 - 2*Q2/E_e/E_beam/4)
E_px = np.sqrt( E_e**2 - E_pz**2)
E_e  = np.sqrt(E_px**2 + E_py**2 + E_pz**2 + me**2)

In [66]:
P_py = 0
P_pz = 0.863 * np.cos(np.radians(44.3887 + 11))
P_px = -0.863 * np.sin(np.radians(44.3887 + 11))
P_e  = np.sqrt(P_px**2 + P_py**2 + P_pz**2 + mp**2)

In [67]:
qprime_py = 0
qprime_pz = 0.18017 * np.cos(np.radians(44.3887 + 246.04485))
qprime_px = -0.18017 * np.sin(np.radians(44.3887 + 246.04485))
qprime_e  = np.sqrt(qprime_px**2 + qprime_py**2 + qprime_pz**2)

In [68]:
assert qprime_e + P_e + E_e - E_beam - mp < 0.001

In [69]:
kdotqprime = E_beam * qprime_e - E_beamx * qprime_px - E_beamy * qprime_py - E_beamz * qprime_pz

In [70]:
kprimedotqprime = E_e * qprime_e - E_px * qprime_px - E_py * qprime_py - E_pz * qprime_pz

In [71]:
np.degrees(np.arccos(1 - 2*Q2/E_e/E_beam/4))

np.float64(7.6946700031425515)

In [72]:
Eetilde      = mp/Mm2 * (E_beam  - Q2/2/mp - kdotqprime/mp)
Eeprimetilde = mp/Mm2 * (E_e     + Q2/2/mp - kprimedotqprime/mp)
deltaEs      = Mm2/2
sinsquared_thetatetilde_half = E_beam * E_e / Eetilde/Eeprimetilde

In [73]:
Q2d = Q2
Ed  = E_beam
Esc = E_e
costel = 1 - Q2d/(2*Ed*Esc)   

In [74]:
cossquared_thetatetilde_half = 1 - sinsquared_thetatetilde_half

In [75]:
delta_r1 = alpha/np.pi * np.log(deltaEs**2 /Eetilde/Eeprimetilde) * (np.log(Q2/me**2)-1)

In [169]:
delta_r2 = alpha/np.pi* (-0.5* (np.log(Eetilde/Eeprimetilde)**2) + 0.5 * np.log(Q2/me**2)**2 - np.pi**2/3 + spence(cossquared_thetatetilde_half))

In [77]:
delta_r1, delta_r2

(np.float64(-0.7203541272750198), np.float64(0.008682782803088377))

In [232]:
delta_vac = alpha/np.pi * (2./3.) * (-5./3. + np.log(Q2/me**2))

In [233]:
delta_vertex = alpha/np.pi * (1.5 * np.log(Q2/me**2) -2 - 0.5*np.log(Q2/me**2)**2 + np.pi**2/6)

In [234]:
delta_r1 + delta_r2 + delta_vertex

np.float64(-0.5712246044707574)

In [235]:
delta_r1 + delta_r2

np.float64(-0.389922885319835)

In [271]:
delta_1 = 2*alpha / np.pi *( np.log(4*deltaEs**2/Q2/x) * np.log(eta) + spence(1-eta/x) - spence(1-1/eta/x))
delta_2 = alpha/np.pi * ( np.log(4*(deltaEs**2)/mp**2) * (P_e/0.863 * np.log(x)-1) + P_e/0.863 * ( -0.5*np.log(x)**2 - np.log(x) * np.log(rho**2/mp**2) + np.log(x) -spencer(1-1/x**2) + 2*spence(-1/x)

In [272]:
rho = np.sqrt(Q2 + 4*mp**2)
Q   = np.sqrt(Q2)
x = ( Q + rho )**2 /4/mp**2
eta = E_beam/E_e

In [281]:
delta_1

np.float64(-0.0014046523249894986)

In [284]:
spence(-1/x)

np.float64(nan)

## Case 2) Marc's paper; Elastic

In [182]:
E_beam   = 0.855
theta_e  = np.radians(52.18)
Q2       = 0.418
E_e      = Q2/E_beam/(4*np.sin(theta_e/2)**2)

In [183]:
E_e

np.float64(0.631937941082835)

In [184]:
E_e = E_beam / ( 1 + E_beam/ (mp * (1-np.cos(theta_e) ) ) )

In [185]:
E_px     = E_e * np.sin(theta_e)
E_py     = 0
E_pz     = E_e * np.cos(theta_e)

In [186]:
P_px     = -E_px
P_py     = 0
P_pz     = E_beam - E_pz
P_e      = np.sqrt(P_px**2 + P_py**2 + P_pz**2 + mp**2)

In [187]:
print(E_beam + mp - E_e - P_e)

0.3514137803771835


In [188]:
deltaEs = 0.01 * ( E_beam - E_e)

In [189]:
sinsquared_thetatetilde_half = np.sin(theta_e/2)**2
cossquared_thetatetilde_half = 1 - sinsquared_thetatetilde_half

In [190]:
delta_r1 = alpha/np.pi * np.log(deltaEs**2 /E_e/E_beam) * (np.log(Q2/me**2)-1)
delta_r2 = alpha/np.pi * (-0.5* (np.log(E_e/E_beam))**2 + 0.5 * np.log(Q2/me**2)**2 - np.pi**2/3 + spence(np.cos(theta_e/2)**2))

In [191]:
delta_r1 + delta_r2

np.float64(-0.040554495337663726)

In [192]:
delta_r2

np.float64(0.22816125521832967)

In [96]:
delta_vac = alpha/np.pi * (2./3.) * (-5./3. + np.log(Q2/me**2))

In [97]:
delta_vac

np.float64(0.01954164085768474)

In [98]:
delta_vertex = alpha/np.pi * (1.5 * np.log(Q2/me**2) -2 - 0.5*np.log(Q2/me**2)**2 + np.pi**2/6)

In [99]:
delta_vertex

np.float64(-0.1880812926773972)

## Case 3 Loop's thesis

In [164]:
Q2 = 0.356
me = 0.5109989461 * 0.001
alpha = 1/137.036
delta_vac = alpha/np.pi * (2./3.) * (-5./3. + np.log(Q2/me**2))

In [165]:
Mm2 = np.sqrt(2)
kdotqprime = E_beam * qprime_e - E_beamx * qprime_px - E_beamy * qprime_py - E_beamz * qprime_pz
Eetilde      = mp/Mm2 * (E_beam  - Q2/2/mp - kdotqprime/mp)
Eeprimetilde = mp/Mm2 * (E_e     + Q2/2/mp - kprimedotqprime/mp)


NameError: name 'qprime_e' is not defined

In [112]:
delta_vertex = alpha/np.pi * (1.5 * np.log(Q2/me**2) -2 - 0.5*np.log(Q2/me**2)**2 + np.pi**2/6)

In [113]:
delta_vertex

np.float64(-0.18334293851140032)

In [166]:
deltaEs  = np.sqrt(2)/2
E_e      = .843
E_beam   = .528
theta_e  = np.radians(53.14)

delta_vertex = alpha/np.pi * (1.5 * np.log(Q2/me**2) -2 - 0.5*np.log(Q2/me**2)**2 + np.pi**2/6)
delta_vac = alpha/np.pi * (2./3.) * (-5./3. + np.log(Q2/me**2))
delta_r1 = alpha/np.pi * np.log(deltaEs**2 /E_e/E_beam) * (np.log(Q2/me**2)-1)
delta_r2 = alpha/np.pi * (-0.5* (np.log(E_e/E_beam))**2 + 0.5 * np.log(Q2/me**2) - np.pi**2/3 + spence(np.cos(theta_e/2)**2))

In [167]:
delta_vertex + delta_vac

np.float64(-0.1640499178487795)

In [168]:
delta_vac + delta_v

NameError: name 'delta_v' is not defined

# MAMI VCS kinematics (Helene's note)

In [59]:
mp = .938272081
me = 0.5109989461 * 0.001
alpha = 1./137.0359895
pi    = 3.141592653589793
alpi  = alpha/pi


E      = 0.843
Eprime = 0.528
thetae = np.radians(53.14)
Q2     = 0.356

In [60]:
delta_vertex = alpha/np.pi * (1.5 * np.log(Q2/me**2) -2 - 0.5*np.log(Q2/me**2)**2 + np.pi**2/6)
delta_vac    = alpha/np.pi * (2./3.) * (-5./3. + np.log(Q2/me**2))

In [61]:
delta_vertex + delta_vac

np.float64(-0.16404993041864635)

In [23]:
Q2

0.356